#ifndef CONFIG_H
#define CONFIG_H

#include "stm32f0xx.h"

// LED configuration
#define LED_GPIO_CLK RCC_AHBPeriph_GPIOB
#define LED_GPIO_PORT GPIOB
#define LED_GPIO_PIN GPIO_Pin_1

#define LED_TASK_NAME "led_task"
#define LED_TASK_PRIORITY 1
#define LED_TASK_STACK_SIZE 32
#define LED_TASK_DELAY 100 // 500ms

// UART configuration
#define UART_GPIO_CLK RCC_AHBPeriph_GPIOA
#define UART_GPIO_PORT GPIOA
#define UART_GPIO_TX_PIN GPIO_Pin_2
#define UART_GPIO_RX_PIN GPIO_Pin_3
#define UART_GPIO_DIR_PIN GPIO_Pin_1 

#define UART_CLK_CMD RCC_APB2PeriphClockCmd
#define UART_CLK RCC_APB2Periph_USART1
#define UART_PERIPH USART1
#define UART_IRQHANDLER USART1_IRQHandler
#define UART_IRQn USART1_IRQn
#define UART_BAUD_RATE 115200

#define UART_RCV_BUFFER_SIZE 64
#define UART_SND_BUFFER_SIZE 64
#define UART_TASK_NAME "uart_task"
#define UART_TASK_PRIORITY 3
#define UART_TASK_STACK_SIZE 64

// MODBUS configuration
#define MODBUS_GPIO_CLK RCC_AHBPeriph_GPIOA
#define MODBUS_GPIO_PORT GPIOA
#define MODBUS_GPIO_OUT0_PIN GPIO_Pin_4
#define MODBUS_GPIO_OUT1_PIN GPIO_Pin_5
#define MODBUS_GPIO_OUT2_PIN GPIO_Pin_6
#define MODBUS_GPIO_OUT3_PIN GPIO_Pin_7
#define MODBUS_GPIO_OUT4_PIN GPIO_Pin_9
#define MODBUS_GPIO_OUT5_PIN GPIO_Pin_10
#define MODBUS_GPIO_NUM 6

#define MODBUS_ADDR (17)

#define MODBUS_TASK_NAME "modbus_task"
#define MODBUS_TASK_PRIORITY 2
#define MODBUS_TASK_STACK_SIZE 64



#endif